# Setup
title: Simple
tagline: A highly customizable jekyll theme
url:
baseurl: "simple-jekyll"
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - tools
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Injamul Mohammad Mollah
  url:
  email: mrinjamul@gmail.com

# Custom vars
version: 1.0.0
