blank_issues_enabled: false
contact_links:
  - name: Mahafujul Haque
    email: emonmondal083@gmail.com
    about: Please ask and answer questions here.
  - name: Injamul Mohammad Mollah
    email: mrinjamul@gmail.com
    about: Please ask and answer questions here.
